version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - SERVER_PORT=3000
      - DATABASE_SERVER=10.199.14.47
      - DATABASE_NAME=GATE_DEV
      - DATABASE_USER=integratif
      - DATABASE_PASSWORD=G3rb4ng!
    command: ["yarn", "start"]

networks:
  backend:
    driver: bridge
volumes:
  node_modules: